### ISSUE TITLE
Check integrity at branch 'Funktionalität'

### ISSUE THREAD

**Issue by ErikWessel** [olivermliu/pavos#8]
+ check spelling & grammar
+ check integrity (missing 'Fehlerbedingung:' at 'Wunschkriterien')
+ check style
+ specify 'Vorbedingung'; 'Nachbedingung'; 'Fehlerbedingung'

**Comment by olivermliu** [comment]
PF1090 doesn't make any sense.
Cluster position calculation should not depend on sensors at all (only lat/lon).
Sensor assignment to a certain cluster should only depend on sensor location, not the specific data or its average.

**Comment by olivermliu** [comment]
Issue at PF1100:
- Cluster size cannot be adjusted in Konfig-GUI, only shape (->PF1110)
- Unclear difference between Cluster position and size - position will define bounds of Cluster

**Comment by olivermliu** [comment]
Please check PF1150, PF1160, PF1170. What is the underlying criterium?

**Comment by Jelumar** [comment]
> Please check PF1150, PF1160, PF1170. What is the underlying criterium?

MK2060?
